# Generated by Django 6.0.2 on 2026-03-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
